name: flutter_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  jwt_decoder: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2
  freezed: ^3.2.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
